networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - client
      - api
    networks:
      - dev
  
  client:
    build:
      context: ./Converter-Client
    networks:
      - dev
  
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    build:
      context: Converter-Server/ConverterAPI
      dockerfile: ./Converter-Server/ConverterAPI/Dockerfile
    ports:
      - "8080:8080"
    container_name: converter_api
    depends_on:
      - aboba_db
    networks:
      - dev

  aboba_db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: abobadb
      POSTGRES_USER: aboba
      POSTGRES_PASSWORD: aboba123
    volumes:
      - aboba_data:/var/lib/postgresql/data
      - ./Converter-Server/ConverterAPI/init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: aboba_db
    networks:
      - dev
volumes:
  aboba_data: